### ISSUE TITLE
What is the structure of the dataset？

### ISSUE THREAD

**Issue by yuyunlong2002** [xiaoaoran/FPS-Net#1]
After I downloaded the code from the website, it did get an error. The reason is that the sequences folder under my data folder is empty. I didn't see the relevant content of the dataset from the README. I want to know that this error is due to me Is it caused by not preparing the data set, and what are the requirements for the data set of the code?

**Comment by xiaoaoran** [comment]
Thanks for your interest in our work. 

You may download SemanticKITTI from [the official website](http://www.semantic-kitti.org/dataset.html#download) and change the dataset path in the config file.

**Comment by yuyunlong2002** [comment]
Hello, I have downloaded Kitti dataset and changed the path of myself.root to the storage path of the dataset in parser.py, but the following error appeared during the program running:
 File "/home/yuyun/anaconda3/envs/FPSNet/lib/python3.7/site-packages/torch/utils/data/ sampler.py", line 66, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
 I suspect I didn't read the Kitti dataset correctly, but I don't know what other places need to be changed based on my own path. Also, in the yaml file of the config folder I did not find the place where the data path is set, can I have more guidance?

**Comment by xiaoaoran** [comment]
Hi, change the working directory first 
```
cd train/task/semantic
```
revise dataset root path in train.sh and run code.
```
./train.sh
```

Same for test.sh

**Comment by xiaoaoran** [comment]
Hi, you may need to change this line into your own path

https://github.com/xiaoaoran/FPS-Net/blob/main/train/tasks/semantic/dataset/kitti/parser.py#L9

Please feel free to contact me if any problems!

**Comment by yuyunlong2002** [comment]
Thank you for your help！ I solved the problem
