### ISSUE TITLE
A problem about the projection of heterogeneous modal graphs in networks

### ISSUE THREAD

**Issue by yuyunlong2002** [xiaoaoran/FPS-Net#2]
Hello, I would like to ask where is the content in the code about converting 3D data into 2D images of different modes you said in your paper，In the FPS net diagram you built, the following parts are shown:
![1](https://user-images.githubusercontent.com/92364188/189805411-4f3da0ad-61b5-433c-bde9-ba5f3a69c732.png)

**Comment by xiaoaoran** [comment]
Hi @yuyunlong2002 

Point cloud projection:
https://github.com/xiaoaoran/FPS-Net/blob/main/train/common/laserscan.py#L111

Corresponding label projection:
https://github.com/xiaoaoran/FPS-Net/blob/main/train/common/laserscan.py#L284

**Comment by xiaoaoran** [comment]
@yuyunlong2002 

I closed this issue since no further questions.

Please feel free to re-open it if any more problems.
