### ISSUE TITLE
A bug occurred when running infer.py in test.sh

### ISSUE THREAD

**Issue by yuyunlong2002** [xiaoaoran/FPS-Net#3]
Sorry to bother you again，When I running your input in test.sh an error occurred in the. py file. There are four variables assigned to a line of code (including proj_output, range_feat, zxy_feat, and resission_feat), but the actual return value of the function is only one (y). I see in your function body that a line of commented content returns four values. How can I solve this problem?
code：https://github.com/xiaoaoran/FPS-Net/blob/main/train/tasks/semantic/modules/user.py#L138
![image](https://user-images.githubusercontent.com/92364188/190893806-4bb39a2a-386f-4110-ab11-13bc032c1b74.png)

Function body return：https://github.com/xiaoaoran/FPS-Net/blob/main/train/tasks/semantic/modules/segmentator.py#L166
![image](https://user-images.githubusercontent.com/92364188/190893802-9058fb6b-ec97-4d30-b6fa-bb5a960ea950.png)

error：
![image](https://user-images.githubusercontent.com/92364188/190893446-e787e71d-5daf-4b1a-98b0-69bccd1e774b.png)

**Comment by xiaoaoran** [comment]
Hi @yuyunlong2002 Thanks for sharing this issue

Yes, please comment this line and uncomment 
```
return y, range, zxy, remission
```

I did some test and forgot to change it back.

**Comment by xiaoaoran** [comment]
Please change the testing code with one output as follows:

https://github.com/xiaoaoran/FPS-Net/blob/main/train/tasks/semantic/modules/user.py#L138
https://github.com/xiaoaoran/FPS-Net/blob/main/train/tasks/semantic/modules/user.py#L140

I did some test and forgot to change them back.

I have updated the code.

**Comment by yuyunlong2002** [comment]
Ok Thank you
